default:
  image: ubuntu:20.04
  cache:
    paths:
    - "~/.cache/pip/"
  before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export TZ=Europe/Berlin
  - apt -y update
  - apt -y install apt-utils
  - apt -y install net-tools python3.8 python3-pip git python3-venv
  - apt -y upgrade
  - git config user.email "gitlab@lrz.de"
  - git config user.name "Gitlab Runner"
  - pip3 install poetry
  - pip3 install django
  - poetry install
  - source $(poetry env info --path)/bin/activate
  - pip3 install django
  - cd django-app
build:
  stage: build
  script:
  - python3 manage.py migrate
  - python3 manage.py check
  - python3 manage.py test

stages:
- build
- test