repos:
  - repo: https://github.com/PyCQA/prospector
    rev: 1.7.5
    hooks:
      - id: prospector
        additional_dependencies:
          - '.[with_mypy,with_bandit]'
        args:
          - --summary-only
          - --zero-exit
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
