# Generated by Django 4.1.3 on 2022-12-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("factchecker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchrequest",
            name="answer",
        ),
        migrations.AddField(
            model_name="searchrequest",
            name="verification_method",
            field=models.CharField(
                default="dpr", help_text="Verification method", max_length=30
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of an article", max_length=30
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="Content of an article", max_length=300
                    ),
                ),
                ("verdict", models.BooleanField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factchecker.searchrequest",
                    ),
                ),
            ],
        ),
    ]
