# Generated by Django 4.1.3 on 2022-12-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factchecker", "0002_remove_searchrequest_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="verdict",
            field=models.CharField(
                help_text="How true the claim is", max_length=10
            ),
        ),
    ]
